[2024-08-04T20:15:11.684+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-04T20:15:11.695+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.carga_dimensao_user_type manual__2024-08-04T20:14:51.720681+00:00 [queued]>
[2024-08-04T20:15:11.698+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.carga_dimensao_user_type manual__2024-08-04T20:14:51.720681+00:00 [queued]>
[2024-08-04T20:15:11.698+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-08-04T20:15:11.704+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): carga_dimensao_user_type> on 2024-08-04 20:14:51.720681+00:00
[2024-08-04T20:15:11.711+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=2289) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-04T20:15:11.713+0000] {standard_task_runner.py:64} INFO - Started process 2291 to run task
[2024-08-04T20:15:11.712+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'carga_dimensao_user_type', 'manual__2024-08-04T20:14:51.720681+00:00', '--job-id', '921', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpe66g20ph']
[2024-08-04T20:15:11.714+0000] {standard_task_runner.py:91} INFO - Job 921: Subtask carga_dimensao_user_type
[2024-08-04T20:15:11.752+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_dag.carga_dimensao_user_type manual__2024-08-04T20:14:51.720681+00:00 [running]> on host 83ccd21ce624
[2024-08-04T20:15:11.807+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gabriel Almeida' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='carga_dimensao_user_type' AIRFLOW_CTX_EXECUTION_DATE='2024-08-04T20:14:51.720681+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-04T20:14:51.720681+00:00'
[2024-08-04T20:15:11.808+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-04T20:15:11.877+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-08-04T20:15:11.900+0000] {logging_mixin.py:188} INFO - Dados inseridos na tabela DimUserType com sucesso.
[2024-08-04T20:15:11.901+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-04T20:15:11.901+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-04T20:15:11.911+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=carga_dimensao_user_type, run_id=manual__2024-08-04T20:14:51.720681+00:00, execution_date=20240804T201451, start_date=20240804T201511, end_date=20240804T201511
[2024-08-04T20:15:11.941+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-04T20:15:11.954+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-04T20:15:11.955+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
