[2024-08-05T00:20:04.073+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-05T00:20:04.107+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.carga_dimensao_user_type manual__2024-08-05T00:19:44.711711+00:00 [queued]>
[2024-08-05T00:20:04.126+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.carga_dimensao_user_type manual__2024-08-05T00:19:44.711711+00:00 [queued]>
[2024-08-05T00:20:04.131+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-08-05T00:20:04.160+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): carga_dimensao_user_type> on 2024-08-05 00:19:44.711711+00:00
[2024-08-05T00:20:04.172+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=4434) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-05T00:20:04.178+0000] {standard_task_runner.py:64} INFO - Started process 4443 to run task
[2024-08-05T00:20:04.178+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'carga_dimensao_user_type', 'manual__2024-08-05T00:19:44.711711+00:00', '--job-id', '1553', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmphtfhizd_']
[2024-08-05T00:20:04.183+0000] {standard_task_runner.py:91} INFO - Job 1553: Subtask carga_dimensao_user_type
[2024-08-05T00:20:04.375+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_dag.carga_dimensao_user_type manual__2024-08-05T00:19:44.711711+00:00 [running]> on host 88edf8e2824b
[2024-08-05T00:20:04.503+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gabriel Almeida' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='carga_dimensao_user_type' AIRFLOW_CTX_EXECUTION_DATE='2024-08-05T00:19:44.711711+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-05T00:19:44.711711+00:00'
[2024-08-05T00:20:04.506+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-05T00:20:04.691+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-08-05T00:20:04.844+0000] {logging_mixin.py:188} INFO - Dados inseridos na tabela DimUserType com sucesso.
[2024-08-05T00:20:04.863+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-05T00:20:04.882+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-05T00:20:05.054+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=carga_dimensao_user_type, run_id=manual__2024-08-05T00:19:44.711711+00:00, execution_date=20240805T001944, start_date=20240805T002004, end_date=20240805T002005
[2024-08-05T00:20:05.259+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-05T00:20:05.356+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
