[2024-08-04T20:57:03.550+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-04T20:57:03.577+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.carga_dimensao_user_type manual__2024-08-04T20:56:42.939088+00:00 [queued]>
[2024-08-04T20:57:03.595+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.carga_dimensao_user_type manual__2024-08-04T20:56:42.939088+00:00 [queued]>
[2024-08-04T20:57:03.595+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-08-04T20:57:03.613+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): carga_dimensao_user_type> on 2024-08-04 20:56:42.939088+00:00
[2024-08-04T20:57:03.630+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=3323) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-04T20:57:03.634+0000] {standard_task_runner.py:64} INFO - Started process 3329 to run task
[2024-08-04T20:57:03.633+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'carga_dimensao_user_type', 'manual__2024-08-04T20:56:42.939088+00:00', '--job-id', '1011', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpdcdwa0rz']
[2024-08-04T20:57:03.637+0000] {standard_task_runner.py:91} INFO - Job 1011: Subtask carga_dimensao_user_type
[2024-08-04T20:57:03.739+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_dag.carga_dimensao_user_type manual__2024-08-04T20:56:42.939088+00:00 [running]> on host 83ccd21ce624
[2024-08-04T20:57:03.902+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gabriel Almeida' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='carga_dimensao_user_type' AIRFLOW_CTX_EXECUTION_DATE='2024-08-04T20:56:42.939088+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-04T20:56:42.939088+00:00'
[2024-08-04T20:57:03.907+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-04T20:57:04.190+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-08-04T20:57:04.390+0000] {logging_mixin.py:188} INFO - Dados inseridos na tabela DimUserType com sucesso.
[2024-08-04T20:57:04.393+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-04T20:57:04.394+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-04T20:57:04.556+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=carga_dimensao_user_type, run_id=manual__2024-08-04T20:56:42.939088+00:00, execution_date=20240804T205642, start_date=20240804T205703, end_date=20240804T205704
[2024-08-04T20:57:04.688+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-04T20:57:04.792+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
