[2024-08-04T22:16:44.276+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-04T22:16:44.306+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.carga_dimensao_company manual__2024-08-04T22:16:23.551150+00:00 [queued]>
[2024-08-04T22:16:44.314+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.carga_dimensao_company manual__2024-08-04T22:16:23.551150+00:00 [queued]>
[2024-08-04T22:16:44.315+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-08-04T22:16:44.326+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): carga_dimensao_company> on 2024-08-04 22:16:23.551150+00:00
[2024-08-04T22:16:44.334+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=175) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-04T22:16:44.337+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'carga_dimensao_company', 'manual__2024-08-04T22:16:23.551150+00:00', '--job-id', '1132', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpqiup1wux']
[2024-08-04T22:16:44.338+0000] {standard_task_runner.py:64} INFO - Started process 179 to run task
[2024-08-04T22:16:44.338+0000] {standard_task_runner.py:91} INFO - Job 1132: Subtask carga_dimensao_company
[2024-08-04T22:16:44.463+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_dag.carga_dimensao_company manual__2024-08-04T22:16:23.551150+00:00 [running]> on host 88edf8e2824b
[2024-08-04T22:16:44.625+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gabriel Almeida' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='carga_dimensao_company' AIRFLOW_CTX_EXECUTION_DATE='2024-08-04T22:16:23.551150+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-04T22:16:23.551150+00:00'
[2024-08-04T22:16:44.628+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-04T22:16:44.882+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-08-04T22:16:44.938+0000] {logging_mixin.py:188} INFO - Dados inseridos na tabela DimCompany com sucesso.
[2024-08-04T22:16:44.939+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-04T22:16:44.939+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-04T22:16:44.983+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=carga_dimensao_company, run_id=manual__2024-08-04T22:16:23.551150+00:00, execution_date=20240804T221623, start_date=20240804T221644, end_date=20240804T221644
[2024-08-04T22:16:45.020+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-04T22:16:45.086+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-04T22:16:45.088+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
