[2024-08-03T09:03:09.806+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-03T09:03:10.086+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.extract_api scheduled__2024-08-03T07:20:00+00:00 [queued]>
[2024-08-03T09:03:10.123+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.extract_api scheduled__2024-08-03T07:20:00+00:00 [queued]>
[2024-08-03T09:03:10.128+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-08-03T09:03:10.211+0000] {taskinstance.py:2330} INFO - Executing <Task(SimpleHttpOperator): extract_api> on 2024-08-03 07:20:00+00:00
[2024-08-03T09:03:10.373+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=2745) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-03T09:03:10.386+0000] {standard_task_runner.py:64} INFO - Started process 2769 to run task
[2024-08-03T09:03:10.444+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'extract_api', 'scheduled__2024-08-03T07:20:00+00:00', '--job-id', '490', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpomx13jp9']
[2024-08-03T09:03:10.458+0000] {standard_task_runner.py:91} INFO - Job 490: Subtask extract_api
[2024-08-03T09:03:10.872+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_dag.extract_api scheduled__2024-08-03T07:20:00+00:00 [running]> on host 69633e19c226
[2024-08-03T09:03:12.705+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gabriel Almeida' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='extract_api' AIRFLOW_CTX_EXECUTION_DATE='2024-08-03T07:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-03T07:20:00+00:00'
[2024-08-03T09:03:12.950+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-03T09:03:13.001+0000] {http.py:173} INFO - Calling HTTP method
[2024-08-03T09:03:13.515+0000] {base.py:84} INFO - Using connection ID 'api_connection' for task execution.
[2024-08-03T09:03:13.758+0000] {base.py:84} INFO - Using connection ID 'api_connection' for task execution.
[2024-08-03T09:03:14.647+0000] {http.py:200} ERROR - HTTP error: Unauthorized
[2024-08-03T09:03:14.697+0000] {http.py:201} ERROR - {"response":{"message":"NÃ£o foram encontrados valores!"}}
[2024-08-03T09:03:14.711+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-03T09:03:15.007+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py", line 198, in check_response
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://app.alunos.me/api/ahoy_viewer_ti

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py", line 170, in execute
    return self.execute_sync(context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py", line 179, in execute_sync
    response = self.hook.run(self.endpoint, self.data, self.headers, self.extra_options)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py", line 188, in run
    return self.run_and_check(session, prepped_request, extra_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py", line 239, in run_and_check
    self.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py", line 202, in check_response
    raise AirflowException(str(response.status_code) + ":" + response.reason)
airflow.exceptions.AirflowException: 401:Unauthorized
[2024-08-03T09:03:15.230+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_dag, task_id=extract_api, run_id=scheduled__2024-08-03T07:20:00+00:00, execution_date=20240803T072000, start_date=20240803T090310, end_date=20240803T090315
[2024-08-03T09:03:15.966+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 490 for task extract_api (401:Unauthorized; 2769)
[2024-08-03T09:03:16.121+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-03T09:03:16.332+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1297: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-08-03T09:03:16.350+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1297: AirflowProviderDeprecationWarning: Call to deprecated class SimpleHttpOperator. (Class `SimpleHttpOperator` is deprecated and will be removed in a future release. Please use `HttpOperator` instead.)
  result = cls.__new__(cls)

[2024-08-03T09:03:16.545+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-03T09:03:16.573+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
