[2024-08-04T22:22:37.488+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-04T22:22:37.504+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.fetch_dim_data manual__2024-08-04T22:22:18.372047+00:00 [queued]>
[2024-08-04T22:22:37.511+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.fetch_dim_data manual__2024-08-04T22:22:18.372047+00:00 [queued]>
[2024-08-04T22:22:37.511+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-08-04T22:22:37.523+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_dim_data> on 2024-08-04 22:22:18.372047+00:00
[2024-08-04T22:22:37.533+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=510) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-04T22:22:37.535+0000] {standard_task_runner.py:64} INFO - Started process 512 to run task
[2024-08-04T22:22:37.535+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'fetch_dim_data', 'manual__2024-08-04T22:22:18.372047+00:00', '--job-id', '1171', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpse55r1g3']
[2024-08-04T22:22:37.536+0000] {standard_task_runner.py:91} INFO - Job 1171: Subtask fetch_dim_data
[2024-08-04T22:22:37.592+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_dag.fetch_dim_data manual__2024-08-04T22:22:18.372047+00:00 [running]> on host 88edf8e2824b
[2024-08-04T22:22:37.664+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gabriel Almeida' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='fetch_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-04T22:22:18.372047+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-04T22:22:18.372047+00:00'
[2024-08-04T22:22:37.666+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-04T22:22:37.677+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-08-04T22:22:37.748+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-04T22:22:37.750+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-04T22:22:37.757+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=fetch_dim_data, run_id=manual__2024-08-04T22:22:18.372047+00:00, execution_date=20240804T222218, start_date=20240804T222237, end_date=20240804T222237
[2024-08-04T22:22:37.803+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-04T22:22:37.823+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-04T22:22:37.824+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
