[2024-08-04T22:30:38.708+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-04T22:30:38.720+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.fetch_dim_data manual__2024-08-04T22:30:17.119912+00:00 [queued]>
[2024-08-04T22:30:38.724+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.fetch_dim_data manual__2024-08-04T22:30:17.119912+00:00 [queued]>
[2024-08-04T22:30:38.724+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-08-04T22:30:38.730+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_dim_data> on 2024-08-04 22:30:17.119912+00:00
[2024-08-04T22:30:38.737+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=758) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-04T22:30:38.738+0000] {standard_task_runner.py:64} INFO - Started process 760 to run task
[2024-08-04T22:30:38.738+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'fetch_dim_data', 'manual__2024-08-04T22:30:17.119912+00:00', '--job-id', '1195', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpk9e62a03']
[2024-08-04T22:30:38.739+0000] {standard_task_runner.py:91} INFO - Job 1195: Subtask fetch_dim_data
[2024-08-04T22:30:38.777+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_dag.fetch_dim_data manual__2024-08-04T22:30:17.119912+00:00 [running]> on host 88edf8e2824b
[2024-08-04T22:30:38.825+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gabriel Almeida' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='fetch_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-04T22:30:17.119912+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-04T22:30:17.119912+00:00'
[2024-08-04T22:30:38.826+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-04T22:30:38.831+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-08-04T22:30:38.906+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-04T22:30:38.908+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-04T22:30:38.915+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=fetch_dim_data, run_id=manual__2024-08-04T22:30:17.119912+00:00, execution_date=20240804T223017, start_date=20240804T223038, end_date=20240804T223038
[2024-08-04T22:30:38.965+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-04T22:30:38.984+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-04T22:30:38.985+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
