[2024-08-05T01:10:13.296+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-05T01:10:13.312+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.carga_fatoemailmarketing scheduled__2024-08-05T01:00:00+00:00 [queued]>
[2024-08-05T01:10:13.318+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.carga_fatoemailmarketing scheduled__2024-08-05T01:00:00+00:00 [queued]>
[2024-08-05T01:10:13.318+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-08-05T01:10:13.325+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): carga_fatoemailmarketing> on 2024-08-05 01:00:00+00:00
[2024-08-05T01:10:13.331+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=793) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-05T01:10:13.333+0000] {standard_task_runner.py:64} INFO - Started process 795 to run task
[2024-08-05T01:10:13.332+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'carga_fatoemailmarketing', 'scheduled__2024-08-05T01:00:00+00:00', '--job-id', '1706', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpbfxeq5lg']
[2024-08-05T01:10:13.334+0000] {standard_task_runner.py:91} INFO - Job 1706: Subtask carga_fatoemailmarketing
[2024-08-05T01:10:13.374+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_dag.carga_fatoemailmarketing scheduled__2024-08-05T01:00:00+00:00 [running]> on host 59ce2ba01338
[2024-08-05T01:10:13.498+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gabriel Almeida' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='carga_fatoemailmarketing' AIRFLOW_CTX_EXECUTION_DATE='2024-08-05T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-05T01:00:00+00:00'
[2024-08-05T01:10:13.500+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-05T01:10:13.549+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-08-05T01:10:13.588+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-05T01:10:13.588+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-05T01:10:13.597+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=carga_fatoemailmarketing, run_id=scheduled__2024-08-05T01:00:00+00:00, execution_date=20240805T010000, start_date=20240805T011013, end_date=20240805T011013
[2024-08-05T01:10:13.639+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-05T01:10:13.670+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-05T01:10:13.671+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
