[2024-08-04T10:59:55.695+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-04T10:59:56.159+0000] {taskinstance.py:2066} INFO - Dependencies not met for <TaskInstance: etl_dag.extract_api scheduled__2024-08-04T09:40:00+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2024-08-04T10:59:56.158434+00:00 and task will be retried at 2024-08-04T11:00:33.118721+00:00.
[2024-08-04T10:59:57.152+0000] {local_task_job_runner.py:163} INFO - Task is not able to be run
