[2024-08-04T22:51:57.814+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-04T22:51:57.826+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.fetch_dim_data manual__2024-08-04T22:51:41.295707+00:00 [queued]>
[2024-08-04T22:51:57.838+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.fetch_dim_data manual__2024-08-04T22:51:41.295707+00:00 [queued]>
[2024-08-04T22:51:57.839+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-08-04T22:51:57.856+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_dim_data> on 2024-08-04 22:51:41.295707+00:00
[2024-08-04T22:51:57.884+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1384) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-04T22:51:57.887+0000] {standard_task_runner.py:64} INFO - Started process 1386 to run task
[2024-08-04T22:51:57.888+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'fetch_dim_data', 'manual__2024-08-04T22:51:41.295707+00:00', '--job-id', '1248', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp0kmgvyhl']
[2024-08-04T22:51:57.889+0000] {standard_task_runner.py:91} INFO - Job 1248: Subtask fetch_dim_data
[2024-08-04T22:51:57.944+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_dag.fetch_dim_data manual__2024-08-04T22:51:41.295707+00:00 [running]> on host 88edf8e2824b
[2024-08-04T22:51:58.066+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gabriel Almeida' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='fetch_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-04T22:51:41.295707+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-04T22:51:41.295707+00:00'
[2024-08-04T22:51:58.068+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-04T22:51:58.077+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-08-04T22:51:58.211+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-04T22:51:58.214+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-04T22:51:58.223+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=fetch_dim_data, run_id=manual__2024-08-04T22:51:41.295707+00:00, execution_date=20240804T225141, start_date=20240804T225157, end_date=20240804T225158
[2024-08-04T22:51:58.274+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-04T22:51:58.309+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-04T22:51:58.311+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
